# Generated by Django 4.0.5 on 2022-06-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorytrackingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='price',
            field=models.IntegerField(),
        ),
    ]
